import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home ({ results }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1>ホットペッパー 沖縄グルメサーチ</h1>
        <ul>
          {results && results.shop ? (
            results.shop.map((data, i) => <li key={i}>{data.name}</li>)
          ) : (
            <li>No data available</li>
          )}
        </ul>
      </main>
    </>
  )
}

// リクエストごとに呼び出されます。
export async function getServerSideProps () {
  const apiKey = process.env.API_KEY
  const baseUrl = 'https://webservice.recruit.co.jp/hotpepper/gourmet/v1/'
  const serviceArea = 'SA98' // サービスエリアを指定
  const format = 'json' // デフォルトがXMLフォーマットなのでJSONを指定

  // 外部APIからデータをFetchします。
  const res = await fetch(
    `${baseUrl}?key=${apiKey}&service_area=${serviceArea}&format=${format}`
  )

  if (!res.ok) {
    console.error(`Failed to fetch data. Status code: ${res.status}`)
    return { props: { results: null } }
  }

  const json = await res.json()
  const { results } = json

  // 上の方にあるHomeにpropsとしてデータが渡されます。
  return { props: { results } }
}
